sudo: false
language: node_js
node_js: "8.1.2"
before_install:
  - npm i -g npm
cache:
  directories:
    - node_modules
script:
  - npm run build
notifications:
  on_failure: change # always|never
  on_success: never
