sudo: false
language: node_js
node_js: "9.4.0"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn
  - yarn build-prod
  - yarn test
notifications:
  on_failure: change # always|never
  on_success: never
